routes:
  - path: "/load-balancing"
    load_balancing:
      method: "round_robin"  # or "random"
      endpoints:
        - "http://user-service-1:8080"
        - "http://user-service-2:8080"
        - "http://user-service-3:8080"
      health_check:
        enabled: true
        path: "/health"
        interval: "10s"
        timeout: "2s"
  - path: "/api/users"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://user-service:8082"
    strip_prefix: true
    require_auth: true
    timeout: 30
    circuit_breaker:
      enabled: true
      threshold: 5
      timeout: 30
      max_concurrent: 100
    rate_limit:
      requests: 100
      period: "minute"

  - path: "/api/products"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://product-service:8083"
    strip_prefix: true
    require_auth: true
    timeout: 30
    cache:
      enabled: true
      ttl: 300
      cache_authenticated: false
    header_transform:
      request:
        "X-Source": "api-gateway"
      response:
        "Cache-Control": "public, max-age=300"

  - path: "/api/orders"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://order-service:8084"
    strip_prefix: true
    require_auth: true
    timeout: 30
    circuit_breaker:
      enabled: true
      threshold: 3
      timeout: 60
      max_concurrent: 50
    retry_policy:
      enabled: true
      attempts: 3
      per_try_timeout: 5
      retry_on: ["connection_error", "server_error"]

  - path: "/api/public"
    methods: ["GET"]
    upstream: "http://public-service:8085"
    strip_prefix: true
    require_auth: false
    timeout: 30
    cache:
      enabled: true
      ttl: 600
      cache_authenticated: false
    rate_limit:
      requests: 500
      period: "minute"

  - path: "/api/search"
    methods: ["GET"]
    upstream: "http://search-service:8087"
    strip_prefix: true
    require_auth: false
    timeout: 45
    rate_limit:
      requests: 50
      period: "minute"
    cache:
      enabled: true
      ttl: 120
      cache_authenticated: false

  - path: "/api/legacy"
    methods: ["GET", "POST"]
    upstream: "http://legacy-service:8088"
    strip_prefix: true
    require_auth: true
    timeout: 60
    url_rewrite:
      patterns:
        - match: "/api/legacy/users/(.*)"
          replacement: "/internal/users/$1"
    header_transform:
      request:
        "X-Legacy-System": "true"
      response:
        "X-Powered-By": ""
      remove: ["Server"]

  - path: "/api/metrics"
    methods: ["GET"]
    upstream: "http://metrics-service:8089"
    strip_prefix: true
    require_auth: true
    timeout: 15
    rate_limit:
      requests: 50
      period: "minute"

  - path: "/scanjobmanager"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://localhost:8001"
    strip_prefix: false
    require_auth: true
    timeout: 30
    rate_limit:
      requests: 2
      period: "minute"
    circuit_breaker:
      enabled: true
      threshold: 5
      timeout: 30
      max_concurrent: 50

  - path: "/ws"
    upstream: "http://websocket-service:8086"
    strip_prefix: false
    require_auth: true
    timeout: 60
    websocket:
      enabled: true
      path: "/ws"
      upstream_path: "/socket"
    circuit_breaker:
      enabled: true
      threshold: 3
      timeout: 60
      max_concurrent: 200
      
  - path: "/health"
    methods: ["GET"]
    upstream: "http://localhost:8080"
    strip_prefix: false
    require_auth: false
    timeout: 5
    cache:
      enabled: false 