services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Auth settings
      - JWT_SECRET=${JWT_SECRET}
      - API_VALIDATION_URL=${API_VALIDATION_URL}
      # Config paths
      - CONFIG_PATH=/app/configs/config.yaml
      - ROUTES_PATH=/app/configs/routes.yaml
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - ENV=production
      - VERSION=0.0.1
      - TRACING_ENDPOINT=http://jaeger:14268/api/traces
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - fixy-scanner-handler_fixy-network
      - fixy-auth_auth-network
      - default

networks:
  fixy-auth_auth-network:
    external: true
  fixy-scanner-handler_fixy-network:
    external: true