version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_VALIDATION_URL=${API_VALIDATION_URL}
      - CONFIG_PATH=/app/configs/config.yaml
      - ROUTES_PATH=/app/configs/routes.yaml
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - ENV=production
      - VERSION=1.0.0
      - TRACING_ENDPOINT=http//jaeger:14268/api/traces
      # Uncomment if you're mounting the IP2Location database from the host
      # - IP2LOCATION_DB_PATH=/app/configs/IP2LOCATION-LITE-DB1.BIN
    volumes:
      - ./configs:/app/configs
      # Uncomment to mount IP2Location database from host
      # - ./IP2LOCATION-LITE-DB1.BIN:/app/configs/IP2LOCATION-LITE-DB1.BIN
    restart: unless-stopped
    networks:
      - fixy-scanner-handler_fixy-network
      - fixy-auth_auth-network
      - default

networks:
  fixy-auth_auth-network:
    external: true
  fixy-scanner-handler_fixy-network:
    external: true