server:
  address: ":8080"
  read_timeout: 30
  write_timeout: 30

auth:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry_hours: 24
  api_key_validation_url: "${API_VALIDATION_URL}"
  api_key_header: "x-api-key"
  jwt_header: "Authorization"

logging:
  level: "${LOG_LEVEL:-info}"
  format: "${LOG_FORMAT:-json}"