server:
  address: "${SERVER_ADDRESS:-:8080}"
  read_timeout: ${SERVER_READ_TIMEOUT:-30}
  write_timeout: ${SERVER_WRITE_TIMEOUT:-30}
  idle_timeout: ${SERVER_IDLE_TIMEOUT:-120}
  max_header_bytes: ${SERVER_MAX_HEADER_BYTES:-1048576}
  enable_http2: ${SERVER_ENABLE_HTTP2:-true}
  enable_compression: ${SERVER_ENABLE_COMPRESSION:-true}

auth:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry_hours: ${JWT_EXPIRY_HOURS:-24}
  api_key_validation_url: "${API_VALIDATION_URL}"
  api_key_header: "${API_KEY_HEADER:-x-api-key}"
  jwt_header: "${JWT_HEADER:-Authorization}"

logging:
  level: "${LOG_LEVEL:-info}"
  format: "${LOG_FORMAT:-json}"
  output: "${LOG_OUTPUT:-stdout}"
  enable_access_log: ${LOG_ENABLE_ACCESS:-true}
  production_mode: ${LOG_PRODUCTION_MODE:-true}
  stacktrace_level: "${LOG_STACKTRACE_LEVEL:-error}"
  sampling:
    enabled: ${LOG_SAMPLING_ENABLED:-true}
    initial: ${LOG_SAMPLING_INITIAL:-100}
    thereafter: ${LOG_SAMPLING_THEREAFTER:-100}
  fields:
    service: "${SERVICE:-api-gateway}"
    environment: "${ENV:-production}"
    version: "${VERSION:-1.0.0}"
  redact:
    - "jwt_secret"
    - "api_key"
    - "authorization"
    - "password"
    - "token"
  max_stacktrace_length: ${LOG_MAX_STACKTRACE_LEN:-2048}

security:
  tls:
    enabled: ${TLS_ENABLED:-false}
    cert_file: "${TLS_CERT_FILE:-/certs/server.crt}"
    key_file: "${TLS_KEY_FILE:-/certs/server.key}"
    min_version: "${TLS_MIN_VERSION:-TLS1.2}"
  enable_xss_protection: ${ENABLE_XSS_PROTECTION:-true}
  enable_frame_deny: ${ENABLE_FRAME_DENY:-true}
  enable_content_type_nosniff: ${ENABLE_CONTENT_TYPE_NOSNIFF:-true}
  enable_hsts: ${ENABLE_HSTS:-true}
  hsts_max_age: ${HSTS_MAX_AGE:-31536000}
  trusted_proxies: ${TRUSTED_PROXIES:-["127.0.0.1", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]}
  max_body_size: ${MAX_BODY_SIZE:-10485760}

cache:
  enabled: ${CACHE_ENABLED:-true}
  default_ttl: ${CACHE_DEFAULT_TTL:-60}
  max_ttl: ${CACHE_MAX_TTL:-3600}
  max_size: ${CACHE_MAX_SIZE:-1000}
  include_host: ${CACHE_INCLUDE_HOST:-true}
  vary_headers: ${CACHE_VARY_HEADERS:-["Accept", "Accept-Encoding", "Authorization"]}
  purge_endpoint: "${CACHE_PURGE_ENDPOINT:-/admin/cache/purge}"

cors:
  enabled: ${CORS_ENABLED:-true}
  allow_all_origins: ${CORS_ALLOW_ALL_ORIGINS:-false}
  allowed_origins: ${CORS_ALLOWED_ORIGINS:-["https://secureguard.oortfy.com", "https://app.oortfy.com", "http://localhost:3000"]}
  allowed_methods: ${CORS_ALLOWED_METHODS:-["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]}
  allowed_headers: ${CORS_ALLOWED_HEADERS:-["Origin", "Content-Type", "Accept", "Authorization", "X-Requested-With", "X-API-Key", "X-API-Auth-Token"]}
  exposed_headers: ${CORS_EXPOSED_HEADERS:-["Content-Length", "Content-Type"]}
  allow_credentials: ${CORS_ALLOW_CREDENTIALS:-true}
  max_age: ${CORS_MAX_AGE:-86400}

metrics:
  enabled: ${METRICS_ENABLED:-true}
  endpoint: "${METRICS_ENDPOINT:-/metrics}"
  include_system: ${METRICS_INCLUDE_SYSTEM:-true}

tracing:
  enabled: ${TRACING_ENABLED:-true}
  provider: "${TRACING_PROVIDER:-jaeger}"
  endpoint: "${TRACING_ENDPOINT:-http://jaeger:14268/api/traces}"
  service_name: "${TRACING_SERVICE_NAME:-api-gateway}"
  sample_rate: ${TRACING_SAMPLE_RATE:-0.1}

etcd:
  hosts: "${ETCD_HOSTS:-127.0.0.1:2379}"