server:
  address: ":8080"
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120
  max_header_bytes: 1048576
  enable_http2: true
  enable_compression: true

auth:
  jwt_secret: "${JWT_SECRET}"
  jwt_expiry_hours: 24
  api_key_validation_url: "${API_VALIDATION_URL}"
  api_key_header: "x-api-key"
  jwt_header: "Authorization"

logging:
  level: "${LOG_LEVEL:-info}"
  format: "${LOG_FORMAT:-json}"
  output: "stdout"
  enable_access_log: true
  production_mode: true
  stacktrace_level: "error"
  sampling:
    enabled: true
    initial: 100
    thereafter: 100
  fields:
    service: "api-gateway"
    environment: "${ENV:-production}"
  redact:
    - "jwt_secret"
    - "api_key"
    - "authorization"
  max_stacktrace_length: 2048

security:
  tls:
    enabled: false
    cert_file: "/certs/server.crt"
    key_file: "/certs/server.key"
    min_version: "TLS1.2"
  enable_xss_protection: true
  enable_frame_deny: true
  enable_content_type_nosniff: true
  enable_hsts: true
  hsts_max_age: 31536000
  trusted_proxies: ["127.0.0.1", "10.0.0.0/8"]
  max_body_size: 10485760

cache:
  enabled: true
  default_ttl: 60
  max_ttl: 3600
  max_size: 1000
  include_host: true
  vary_headers: ["Accept", "Accept-Encoding", "Authorization"]
  purge_endpoint: "/admin/cache/purge"

cors:
  enabled: true
  allow_all_origins: false
  allowed_origins: ["https://secureguard.oortfy.com", "https://app.oortfy.com", "http://localhost:3000"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
  allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization", "X-Requested-With", "X-API-Key", "X-API-Auth-Token"]
  exposed_headers: ["Content-Length", "Content-Type"]
  allow_credentials: true
  max_age: 86400

metrics:
  enabled: true
  endpoint: "/metrics"
  include_system: true

tracing:
  enabled: true
  provider: "jaeger"
  endpoint: "${TRACING_ENDPOINT:-http://jaeger:14268/api/traces}"
  service_name: "api-gateway"
  sample_rate: 0.1