routes:
  - path: "/scanjobmanager"
    upstream: "http://localhost:8001"
    methods: ["GET", "POST", "PUT", "DELETE"]
    load_balancing:
      method: "round_robin"
      health_check: true
      endpoints:
        - "http://localhost:8001"
        - "http://localhost:8002"
      health_check_config:
        path: "/scanjobmanager/health"
        interval: 10
        timeout: 2
    rate_limit:
      requests_per_minute: 1000
    circuit_breaker:
      enabled: true
      threshold: 10
      timeout: 30
      max_concurrent: 3
    retry_policy:
      max_attempts: 3
      initial_interval: 1
      max_interval: 5
      multiplier: 2.0
      retry_on_status_codes: [500, 502, 503, 504]
    require_auth: true