routes:
  - path: "/api/users"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://user-service:8082"
    strip_prefix: true
    require_auth: true
    timeout: 30

  - path: "/api/products"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://product-service:8083"
    strip_prefix: true
    require_auth: true
    timeout: 30

  - path: "/api/orders"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://order-service:8084"
    strip_prefix: true
    require_auth: true
    timeout: 30

  - path: "/api/public"
    methods: ["GET"]
    upstream: "http://public-service:8085"
    strip_prefix: true
    require_auth: false
    timeout: 30

  - path: "/scanjobmanager"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://localhost:8001"
    strip_prefix: false
    require_auth: true
    timeout: 30

  - path: "/ws"
    upstream: "http://websocket-service:8086"
    strip_prefix: false
    require_auth: true
    timeout: 60
    websocket:
      enabled: true
      path: "/ws"
      upstream_path: "/socket" 