routes:
  - path: "/scanjobmanager"
    methods: ["GET", "POST", "PUT", "DELETE"]
    upstream: "http://localhost:8001"
    strip_prefix: false
    require_auth: true
    timeout: 30
    rate_limit:
      requests: 1000
      period: "minute"
    circuit_breaker:
      enabled: true
      threshold: 10
      timeout: 30
      max_concurrent: 3