routes:
  - path: "/auth/*"
    upstream: "http://auth-service:8000"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    protocol: HTTP
    strip_prefix: false
    timeout: 120
    middlewares:
      require_auth: false
      rate_limit:
        requests: 100000
        period: "minute"
      circuit_breaker:
        enabled: true
        threshold: 5
        timeout: 30
        max_concurrent: 100
      retry_policy:
        enabled: true
        attempts: 3
        per_try_timeout: 5
        retry_on: ["connection_error", "server_error"]

  - path: "/scanjobmanager/*"
    upstream: "http://scanjobmanager:8001"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    protocol: HTTP
    strip_prefix: false
    timeout: 120
    middlewares:
      require_auth: true
      rate_limit:
        requests: 100000
        period: "minute"
      circuit_breaker:
        enabled: true
        threshold: 5
        timeout: 30
        max_concurrent: 100
      retry_policy:
        enabled: true
        attempts: 3
        per_try_timeout: 5
        retry_on: ["connection_error", "server_error"]

  - path: "/project"
    upstream: "http://host.docker.internal:8002"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    protocol: HTTP
    strip_prefix: false
    timeout: 120
    middlewares:
      require_auth: true
      rate_limit:
        requests: 100000
        period: "minute"
      circuit_breaker:
        enabled: true
        threshold: 5
        timeout: 30
        max_concurrent: 100
      retry_policy:
        enabled: true
        attempts: 3
        per_try_timeout: 5
        retry_on: ["connection_error", "server_error"]