name: Go Build

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        check-latest: true
    
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: go mod download
    
    - name: Build application
      run: make build
    
    - name: Verify application binary
      run: |
        if [ ! -f "bin/apigateway" ]; then
          echo "Application binary not found"
          exit 1
        fi
        echo "Application binary successfully built"
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: apigateway-binary
        path: bin/apigateway
        retention-days: 5

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: apigateway:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max 